import * as z from "zod";

export const formSchema = z.object({
  prompt: z.string().min(1, { message: " Image Prompt is required" }),
  resolution: z.string().min(1),
  amount: z.string().min(1), // Add this line
});

export const amountOptions = [
  {
    value: "1",
    label: "1 Photo",
  },
  {
    value: "2",
    label: "2 Photos",
  },
  {
    value: "3",
    label: "3 Photos",
  },
  {
    value: "4",
    label: "4 Photos",
  },
 
];

export const resolutionOptions = [
  {
    value: "4:3",
    label: "4:3",
  },,
  {
    value: "9:16",
    label: "9:16",
  },
  {
    value: "1:1",
    label: "1:1",
  },
  {
    value: "3:2",
    label: "3:2",
  },
  {
    value: "7:4",
    label: "7:4",
  },
  {
    value: "4:5",
    label: "4:5",
  },
];

export const imagePrompts = [
  "Create a landscape in the style of Claude Monet.",
  "Design a self-portrait inspired by Frida Kahlo.",
  "Compose an abstract piece in the vein of Jackson Pollock.",
  "Develop a still life painting mimicking the style of Paul Cézanne.",
  "Craft a surrealist scene influenced by Salvador Dalí.",
  "Design a work inspired by the Cubism of Pablo Picasso.",
  "Create an image in the colorful, geometric style of Piet Mondrian.",
  "Craft a Pop Art piece in the style of Andy Warhol.",
  "Develop a work inspired by Vincent van Gogh's Starry Night.",
  "Compose a piece with the pointillism technique of Georges Seurat.",
  "Create an urban scene influenced by Edward Hopper.",
  "Develop a nature painting in the style of Georgia O'Keeffe.",
  "Design a social critique inspired by Banksy.",
  "Craft an image in the minimalist style of Agnes Martin.",
  "Create a work in the style of Leonardo da Vinci's sketches.",
  "Compose an expressionist piece inspired by Edvard Munch.",
  "Design an architectural drawing in the style of Frank Lloyd Wright.",
  "Create an artwork in the dream-like style of Marc Chagall.",
  "Develop a romantic painting influenced by John Constable.",
  "Craft an image in the Fauvism style of Henri Matisse.",
  "Design a work based on the sculptures of Auguste Rodin.",
  "Create an interior scene in the style of Johannes Vermeer.",
  "Compose a coastal painting inspired by J.M.W. Turner.",
  "Design an optical illusion in the style of M.C. Escher.",
  "Craft a work in the photo-realistic style of Chuck Close.",
  "Develop an image in the pop surrealism style of Mark Ryden.",
  "Create a piece inspired by the Art Nouveau works of Alphonse Mucha.",
  "Design a work in the mixed-media style of Robert Rauschenberg.",
  "Craft an image in the naturalistic style of John James Audubon.",
  "Compose a figurative painting in the style of Lucian Freud.",
  "Create a work inspired by the ink drawings of Aubrey Beardsley.",
  "Develop a piece in the style of Hieronymus Bosch's fantastical scenes.",
  "Craft an image in the splatter paint style of Sam Francis.",
  "Design a work inspired by the collages of Hannah Höch.",
  "Create an urban mural in the style of Jean-Michel Basquiat.",
  "Develop a work in the Op Art style of Bridget Riley.",
  "Compose an image in the pastel style of Edgar Degas.",
  "Design a work in the style of the Japanese Ukiyo-e prints.",
  "Craft an image inspired by the Abstract Expressionism of Willem de Kooning.",
  "Create a landscape painting in the American Regionalism style of Grant Wood.",
  "Develop an image inspired by the early photography of Ansel Adams.",
  "Design a work in the Impressionist style of Camille Pissarro.",
  "Compose a piece in the Classical style of Jacques-Louis David.",
  "Craft a work influenced by the landscapes of Albert Bierstadt.",
  "Develop an image in the Symbolist style of Gustav Klimt.",
  "Create an artwork inspired by the fashion illustrations of René Gruau.",
  "Design a piece in the style of the Renaissance frescoes.",
  "Craft an image in the Constructivist style of El Lissitzky.",
  "Develop a portrait in the style of Amedeo Modigliani.",
  "Compose a modern artwork inspired by the movements of Wassily Kandinsky.",
  "A sunrise over a tranquil lake with mist rising from the water. (Claude Monet)",
  "A waterfall cascading through a lush, tropical forest. (Henri Rousseau)",
  "A mountain range under a starry night sky. (Vincent van Gogh)",
  "A blooming cherry blossom garden in spring. (Katsushika Hokusai)",
  "An old, cobblestone street in a European village. (Maurice Utrillo)",
  "A field of lavender swaying in a light breeze. (Mary Cassatt)",
  "A snowy landscape illuminated by the Northern Lights. (Frederic Edwin Church)",
  "A coral reef teeming with marine life. (Raymond Harris-Ching)",
  "A panoramic view of a bustling city skyline at dusk. (Edward Hopper)",
  "A serene Japanese Zen garden. (Tawaraya Sōtatsu)",
  "A desert landscape with towering sand dunes. (Georgia O'Keeffe)",
  "A historic castle surrounded by a moat. (J.M.W. Turner)",
  "An idyllic, secluded beach with crystal-clear waters. (Winslow Homer)",
  "A bustling marketplace in an exotic location. (Jean-Léon Gérôme)",
  "A quiet country road lined with autumn foliage. (Camille Pissarro)",
  "A palm-fringed oasis in the middle of a desert. (David Hockney)",
  "A picturesque vineyard with rolling hills in the background. (Thomas Kinkade)",
  "A traditional tea ceremony in an ornate room. (Utamaro Kitagawa)",
  "An aerial view of meandering rivers through a rainforest. (Peter Doig)",
  "A tranquil pond with floating lotus flowers. (Childe Hassam)",
  "A foggy morning in a quaint harbor town. (Andrew Wyeth)",
  "A moonlit path through a forest blanketed with snow. (Ivan Shishkin)",
  "An old lighthouse standing against turbulent seas. (Joaquín Sorolla)",
  "A medieval village square with a historic fountain. (Pieter Bruegel the Elder)",
  "A cobblestone bridge crossing a slow-moving stream. (John Constable)",
  "A treetop view of a tropical rainforest canopy. (Rousseau)",
  "A sprawling savannah with roaming wildlife. (Charles Marion Russell)",
  "A bustling cafe scene in Paris with the Eiffel Tower in the background. (Édouard Manet)",
  "A majestic cliff overlooking the ocean with waves crashing below. (Albert Bierstadt)",
  "A tranquil monastery high up in the mountains. (Nicholas Roerich)",
  "An intimate jazz club with musicians in full swing. (Romare Bearden)",
  "A hot air balloon festival with colorful balloons filling the sky. (Yoko Honda)",
  "An ornate temple with intricate carvings and gold trim. (Jean-Auguste-Dominique Ingres)",
  "A fiery sunset over a barren landscape. (Tom Thomson)",
  "A cozy cabin in the woods surrounded by autumn leaves. (Grant Wood)",
  "A sunken pirate ship lying on the ocean floor. (Howard Pyle)",
  "A futuristic cityscape with neon lights and flying cars. (Yoko Honda)",
  "A spring meadow filled with blooming wildflowers. (Marc Chagall)",
  "An ethereal underwater cave illuminated by rays of sunlight. (Dale Chihuly)",
  "A lively street festival with dancers and musicians. (Diego Rivera)",
  "A colorful coral garden under the sea. (Henri Matisse)",
  "A panoramic mountain vista with a glacier-fed river. (Bob Ross)",
  "A narrow, winding road through a dense forest. (Ivan Shishkin)",
  "A panoramic view of a valley filled with morning fog. (Caspar David Friedrich)",
  "A historic library with walls lined with ancient books. (Johannes Vermeer)",
  "An inviting campfire by a lake with canoes pulled ashore. (Winslow Homer)",
  "A vibrant, bustling Tokyo street at night. (Takashi Murakami)",
  "A view from a mountaintop with clouds below. (René Magritte)",
  "A winding path through a magical, enchanted forest. (Maxfield Parrish)",
  "An abandoned amusement park reclaimed by nature. (Banksy)",
  "A bustling alien marketplace. (H.R. Giger)",
  "A dragon guarding its hoard in a cavern. (J.R.R. Tolkien)",
  "A lavish ballroom in a fantasy kingdom. (John Singer Sargent)",
  "An explorer discovering a hidden underwater city. (Jules Verne)",
  "A haunted house with spectral apparitions. (Edward Hopper)",
  "A sky filled with floating islands. (Roger Dean)",
  "A futuristic city with hovering vehicles. (Syd Mead)",
  "An enchanted forest with talking animals. (Beatrix Potter)",
  "A secret lab where time travel is being developed. (H.G. Wells)",
  "A barren, post-apocalyptic landscape. (Salvador Dalí)",
  "A fairy ring in a moonlit forest. (Brian Froud)",
  "An abandoned amusement park reclaimed by nature. (Banksy)",
  "A library filled with magical tomes. (Jorge Luis Borges)",
  "An ancient temple hiding deadly traps. (Indiana Jones)",
  "A spaceship navigating an asteroid field. (Ralph McQuarrie)",
  "A sorcerer's tower with mystical artifacts. (Hieronymus Bosch)",
  "A cyberpunk cityscape filled with neon signs. (Katsuhiro Otomo)",
  "A scene from a medieval jousting tournament. (Leonardo da Vinci)",
  "A castle floating on clouds. (Hayao Miyazaki)",
  "An army of robots invading a city. (Isaac Asimov)",
  "A demonic ritual in a secluded lair. (H.P. Lovecraft)",
  "A giant creature slumbering in a mountain range. (Jack Kirby)",
  "A landscape inside a magical snow globe. (Thomas Kinkade)",
  "An oasis in a magical desert. (Georgia O'Keeffe)",
  "A steampunk factory churning out automatons. (Terry Gilliam)",
  "A parallel universe connected through a portal. (Stephen King)",
  "An eternal battlefield in a land of gods and monsters. (Edvard Munch)",
  "An urban legend's lair filled with mysterious items. (Tim Burton)",
  "A meeting between intergalactic diplomats. (Pablo Picasso)",
  "A kingdom hidden within a massive tree. (Frida Kahlo)",
  "A cavern filled with bioluminescent flora and fauna. (Claude Monet)",
  "A lost city covered in vines and foliage. (Henri Rousseau)",
  "A parade in a dystopian society. (George Orwell)",
  "An island that exists in both the past and the future. (M.C. Escher)",
  "A lavish throne room with a hidden secret. (Rembrandt)",
  "A celestial palace on a distant planet. (Vincent van Gogh)",
  "A gang of space pirates boarding a luxury cruiser. (Howard Pyle)",
  "A clash between mythical creatures in an enchanted forest. (Arthur Rackham)",
  "A scene from a high-stakes heist in a magical kingdom. (Albrecht Dürer)",
  "A villain's grand chamber filled with twisted inventions. (M.C. Escher)",
  "A mountain pass that alters reality. (René Magritte)",
  "A carnival where wishes are granted, for a price. (Edgar Allan Poe)",
  "A lighthouse that attracts supernatural beings. (James Whistler)",
  "A witches' coven meeting in a secret forest clearing. (Francisco Goya)",
  "A landscape where the elements are personified. (Sandro Botticelli)",
  "A futuristic colosseum with bizarre challenges. (Jean Giraud - Moebius)",
  "A cursed pirate ship emerging from a foggy sea. (N.C. Wyeth)",
  "An underground maze filled with magical obstacles. (Peter Paul Rubens)",
  "A serene Zen garden in a future metropolis. (Jackson Pollock)",
  "A treasure hunter discovering a room of illusions. (Jan van Eyck)",
  "A nomadic tribe traversing a frozen tundra. (Ansel Adams)",
  "An aerial view of a labyrinthine hedge maze. (Stanley Kubrick)",
  "A serene monastery high atop a mountain range. (Hokusai)",
  "A cavern lit by crystals, harboring ancient secrets. (Michelangelo)",
  "An underwater realm ruled by merfolk. (J.M.W. Turner)",
  "A lone knight confronting a fearsome dragon. (Frank Frazetta)",
  "A winter wonderland ruled by a Snow Queen. (Tove Jansson)",
  "An urban landscape overrun by nature. (Yoko Honda)",
  "A bustling marketplace in a magical realm. (Pieter Bruegel the Elder)",
  "A secret garden hidden behind an ancient castle. (John Constable)",
  "A space station orbiting a gas giant. (Chris Foss)",
  "A high-speed train in a cyberpunk city. (Hajime Sorayama)",
  "An epic space battle between rival star fleets. (Lebbeus Woods)",
  "An oracle's cave filled with enchanted objects. (Alphonse Mucha)",
  "A tranquil village in a land of eternal twilight. (Grant Wood)",
  "A hidden vault containing arcane knowledge. (Mary Blair)",
  "A forest path leading to an alternate dimension. (Max Ernst)",
  "A Roman gladiator arena reimagined in the future. (Zdzisław Beksiński)",
  "An arctic base on a distant ice planet. (E. H. Shepard)",
  "A lonely astronaut marooned on a barren moon. (Norman Rockwell)",
  "A panoramic view of a Mars colony. (Robert McCall)",
  "A medieval cathedral transformed into a fortress. (Gothic Architecture)",
  "A subterranean city illuminated by magma. (Giger)",
  "An aerial dogfight between dragon riders. (Ray Harryhausen)",
  "A sacred temple surrounded by cherry blossoms. (Utagawa Hiroshige)",
  "A futuristic zoo featuring mythical creatures. (Charley Harper)",
  "A necromancer's lair filled with forbidden scrolls. (Lucas Cranach the Elder)",
  "A stone circle that serves as a portal to other worlds. (Andy Goldsworthy)",
  "A seance conducted in a Victorian drawing room. (John Atkinson Grimshaw)",
  "A dystopian arena where participants battle with magic. (Frank Miller)",
  "A lush garden growing in an abandoned subway station. (Marc Chagall)",
  "A Venetian carnival with supernatural participants. (Canaletto)",
  "A war council held in the heart of a volcano. (Caravaggio)",
  "A mysterious pyramid surrounded by a deadly jungle. (Frida Kahlo)",
  "A prison in another dimension that holds cosmic entities. (Pablo Picasso)",
  "A magical duel taking place on a floating platform. (Diego Velázquez)",
  "A factory where dreams are manufactured. (Salvador Dalí)",
  "A bridge connecting two parallel universes. (Claude Monet)",
  "A monumental sculpture that controls time. (Henry Moore)",
  "A cabal of wizards plotting in a secret chamber. (Albert Bierstadt)",
  "A floating city suspended by anti-gravity technology. (Kazimir Malevich)",
  "An ancient Greek temple housing a modern supercomputer. (Jean-Auguste-Dominique Ingres)",
  "A haunted library filled with cursed books. (Winslow Homer)",
  "An occult museum storing dangerous artifacts. (Tsukioka Yoshitoshi)",
  "A stage for a play that manipulates reality. (Edward Gordon Craig)",
  "A celestial armada preparing for intergalactic war. (Nicholas Roerich)",
  "An intricate clock tower that can rewind time. (Leonardo da Vinci)",
  "A night market that only appears during a full moon. (Marc Chagall)",
  "A cosmic whirlpool at the edge of the universe. (Vincent van Gogh)",
  "A smuggler's den hidden behind a waterfall. (Thomas Cole)",
];

/*
  export const formSchema = z.object({
  promp: z.string().min(1, { message: 'Prompt is required' }),
  name: z.string(),
  description: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  deletedAt: z.string().nullable(),
  workspaceId: z.string(),
  workspace: z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
    deletedAt: z.string().nullable(),
    userId: z.string(),
  }),
  messages: z.array(
    z.object({
      id: z.string(),
      text: z.string(),
      createdAt: z.string(),
      updatedAt: z.string(),
      deletedAt: z.string().nullable(),
      conversationId: z.string(),
      conversation: z.object({
        id: z.string(),
        name: z.string(),
        description: z.string(),
        createdAt: z.string(),
        updatedAt: z.string(),
        deletedAt: z.string().nullable(),
        workspaceId: z.string(),
      }),
      userId: z.string(),
      user: z.object({
        id: z.string(),
        email: z.string(),
        firstName: z.string(),
        lastName: z.string(),
        createdAt: z.string(),
        updatedAt: z.string(),
        deletedAt: z.string().nullable(),
      }),
    }),
  ),
});

export type FormSchema = z.infer<typeof formSchema>;

*/